import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import classes from "./layout.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={classes.header}>
          <h2 id="nav-title">Gunja.DEV</h2>
          <nav>
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/components/todo">Todo</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className={classes.main}>{children}</main>
      </body>
    </html>
  );
}
